typename: gallery
title: "Image Gallery"
description: "Display a collection of images on your page"
icon: "bi bi-images"
custom_html: true
ignore_container: true

# Include libraries that come preloaded
include_libraries:
  jquery: true
  sweetalert: true
  fontawesome: true